[package]
name = "scoped-css-macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1"
unsynn = "0"
proc-macro2 = { version = "1", features = ["span-locations"] }
lightningcss = "1.0.0-alpha.68"
