[package]
name = "example"
version = "0.1.0"
edition.workspace = true

[dependencies]
scoped-css = { path = "../.." }
scoped-css-core = { path = "../../scoped-css-core" }

[build-dependencies]
scoped-css-build = { path = "../../scoped-css-build" }
